DROP DATABASE IF EXISTS Przychodnia;

CREATE DATABASE Przychodznia;
USE Przychodnia;


DROP TABLE Pacjenci;

CREATE TABLE Pacjenci 
(`IDPacjent` INT  NOT NULL AUTO_INCREMENT,
`Imie` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Nazwisko` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`PESEL` VARCHAR(11) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Adres` text CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Ubepiecznie` int(11) NOT NULL,
`IDLekarz` INT  NOT NULL,
`IDPielegniarka` INT  NOT NULL,
PRIMARY KEY(`IDPacjent`))
DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;

DROP TABLE Lekarze;

CREATE TABLE Lekarze
(`IDLekarz` INT  NOT NULL AUTO_INCREMENT,
`Specjalizacja` text CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Imie` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Nazwisko` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`PESEL` VARCHAR(11) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Adres` text CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Telefon` text CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`IloscPacjentow` INT  NOT NULL,
PRIMARY KEY(`IDLekarz`))
DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;

DROP TABLE Recepty;

CREATE TABLE Recepty
(`IDRecepty` INT  NOT NULL AUTO_INCREMENT,
`IDLekarz` INT  NOT NULL,
`IDWizyty` INT  NOT NULL,
`DataWystawienia` date NOT NULL,
`JednostkaChorobowa` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Lek` text CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Firma` text CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
PRIMARY KEY(`IDRecepty`))
DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;

DROP TABLE Activity;

CREATE TABLE Activity
(`IDAcivity` INT  NOT NULL AUTO_INCREMENT,
`IDPacjent` INT  NOT NULL,
`IDLekarz` INT  NOT NULL,
`IDWizyty` INT  NOT NULL,
`DataWystawienia` date NOT NULL,
`JednostkaChorobowa` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Lek` text CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Firma` text CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
PRIMARY KEY(`IDActivity`))
DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;
